cloud:
  aws:
    credentials:
      access-key: aws-key
      secret-key: aws-key
    region:
      static: us-east-1

application:
  bucket:
    name: s3-file-upload-v1

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
